
import type { Stack, Template } from './types';

export const TRENDING_TEMPLATE_IDS: string[] = [
  'flex_template_5',        // Private Jet Lifestyle
  'flex_template_13',       // Infinity Pool Villa
  'aesthetics_template_20', // Dramatic Studio Portrait
  'flex_template_18',       // Race Track Ferrari
  'celebration_template_3', // Cozy Christmas Portrait
  'clothes_template_9',     // Summer Linen
  'monuments_template_5',   // Great Wall of China Trek
  'sceneries_template_2',   // Sahara Desert Walk
];

export const STACKS: Stack[] = [
  { id: 'fitit', name: 'Fitit', imageUrl: '/images/fitit_cover.png' },
  { id: 'animation', name: 'Animation', imageUrl: 'https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?q=80&w=1200&auto=format&fit=crop' },
  { id: 'aesthetics', name: 'Aesthetics', imageUrl: '/images/asthetics_cover.png' },
  { id: 'celebration', name: 'Celebration', imageUrl: '/images/celebration_cover.png' },
  { id: 'clothes', name: 'Clothes', imageUrl: '/images/clothes_cover.png' },
  { id: 'flex', name: 'Flex', imageUrl: '/images/flex_cover.png' },
  { id: 'monuments', name: 'Monuments', imageUrl: '/images/monuments_cover.png' },
  { id: 'sceneries', name: 'Sceneries', imageUrl: '/images/sceneries_cover.png' },
];

const fititTemplates: Template[] = [
  {
    id: 'fitit_template_1',
    name: 'Lower-Wear',
    stackId: 'fitit',
    imageUrl: '/images/fitit_lowerwear_cover.jpg',
    prompt: "Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. **OBJECTIVE: EXECUTE A TECHNICAL 'VIRTUAL TRY-ON' COMPOSITE.**\n\n**INPUT ANALYSIS:**\n*   **INPUT 1 (The User):** This image contains the definitive person. EVERY aspect of this person (face, hair, skin, body shape, proportions, pose) is the ABSOLUTE SOURCE OF TRUTH. It must be preserved with 100% fidelity.\n*   **INPUT 2 (The Garment):** This image is ONLY a reference for the clothing item. The person, background, and any other elements in this image are IRRELEVANT DATA and MUST BE COMPLETELY DISCARDED.\n\n**CORE MANDATE: ZERO FACIAL MODIFICATION. THIS IS NON-NEGOTIABLE.**\nThe face, head, and hair from INPUT 1 must be transferred to the output image with ZERO changes. This is not a blending operation. It is a strict copy-and-paste of the user's identity. Any influence from the face in INPUT 2 is a critical failure.\n\n**STEP-BY-STEP EXECUTION PROTOCOL:**\n1.  **PRE-PROCESSING:** Mentally isolate the lower-body clothing item (e.g., pants, jeans, skirt) from INPUT 2. Discard every other pixel from INPUT 2, especially the person wearing it. You are now working with the user from INPUT 1 and the isolated garment.\n2.  **IDENTIFY TARGET AREA:** On the user from INPUT 1, identify the area covered by their current clothing. This is the only area that can be modified.\n3.  **COMPOSITE:** Layer the isolated garment from step 1 over the target area on the user from INPUT 1.\n4.  **ADAPT GARMENT:** Warp, resize, and adjust the lighting on the NEW GARMENT ONLY to fit the user's exact body shape, size, and pose from INPUT 1. The user's body CANNOT be changed to fit the garment.\n5.  **FINAL VERIFICATION:** Before outputting, verify that the face, head, hair, and all visible skin in the final image are a 100% pixel-identical match to INPUT 1.\n\n**OUTPUT:**\nGenerate four full-body output images from different fashion-catalog angles: a front view (standing), a side view, a back view, and a semi-profile view. Use a neutral studio background for all outputs.",
    aspectRatio: '3:4',
  },
  {
    id: 'fitit_template_2',
    name: 'Upper-Wear',
    stackId: 'fitit',
    imageUrl: '/images/fitit_upperwear_cover.jpg',
    prompt: "Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. **OBJECTIVE: EXECUTE A TECHNICAL 'VIRTUAL TRY-ON' COMPOSITE.**\n\n**INPUT ANALYSIS:**\n*   **INPUT 1 (The User):** This image contains the definitive person. EVERY aspect of this person (face, hair, skin, body shape, proportions, pose) is the ABSOLUTE SOURCE OF TRUTH. It must be preserved with 100% fidelity.\n*   **INPUT 2 (The Garment):** This image is ONLY a reference for the clothing item. The person, background, and any other elements in this image are IRRELEVANT DATA and MUST BE COMPLETELY DISCARDED.\n\n**CORE MANDATE: ZERO FACIAL MODIFICATION. THIS IS NON-NEGOTIABLE.**\nThe face, head, and hair from INPUT 1 must be transferred to the output image with ZERO changes. This is not a blending operation. It is a strict copy-and-paste of the user's identity. Any influence from the face in INPUT 2 is a critical failure.\n\n**STEP-BY-STEP EXECUTION PROTOCOL:**\n1.  **PRE-PROCESSING:** Mentally isolate the upper-body garment from INPUT 2. Discard every other pixel from INPUT 2, especially the person wearing it. You are now working with the user from INPUT 1 and the isolated garment.\n2.  **IDENTIFY TARGET AREA:** On the user from INPUT 1, identify the area covered by their current clothing. This is the only area that can be modified.\n3.  **COMPOSITE:** Layer the isolated garment from step 1 over the target area on the user from INPUT 1.\n4.  **ADAPT GARMENT:** Warp, resize, and adjust the lighting on the NEW GARMENT ONLY to fit the user's exact body shape, size, and pose from INPUT 1. The user's body CANNOT be changed to fit the garment.\n5.  **FINAL VERIFICATION:** Before outputting, verify that the face, head, hair, and all visible skin in the final image are a 100% pixel-identical match to INPUT 1.\n\n**OUTPUT:**\nGenerate four output images from different angles: a front view (standing), a 3/4 left view, a right side view (arms crossed), and a seated view. Use a neutral studio background for all outputs.",
    aspectRatio: '3:4',
  },
  {
    id: 'fitit_template_3',
    name: 'Innerwear',
    stackId: 'fitit',
    imageUrl: '/images/fitit_innerwear_cover.jpg',
    prompt: "Ensure the output figure's face and hairstyle matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. **OBJECTIVE: EXECUTE A TECHNICAL 'VIRTUAL TRY-ON' COMPOSITE.**\n\n**INPUT ANALYSIS:**\n*   **INPUT 1 (The User):** This image contains the definitive person. EVERY aspect of this person (face, hair, skin, body shape, proportions, pose) is the ABSOLUTE SOURCE OF TRUTH. It must be preserved with 100% fidelity.\n*   **INPUT 2 (The Garment):** This image is ONLY a reference for the clothing item. The person, background, and any other elements in this image are IRRELEVANT DATA and MUST BE COMPLETELY DISCARDED.\n\n**CORE MANDATE: ZERO FACIAL MODIFICATION. THIS IS NON-NEGOTIABLE.**\nThe face, head, and hair from INPUT 1 must be transferred to the output image with ZERO changes. This is not a blending operation. It is a strict copy-and-paste of the user's identity. Any influence from the face in INPUT 2 is a critical failure.\n\n**STEP-BY-STEP EXECUTION PROTOCOL:**\n1.  **PRE-PROCESSING:** Mentally isolate the innerwear/clothing item from INPUT 2. Discard every other pixel from INPUT 2, especially the person wearing it. You are now working with the user from INPUT 1 and the isolated garment.\n2.  **IDENTIFY TARGET AREA:** On the user from INPUT 1, identify the area covered by their current clothing. This is the only area that can be modified.\n3.  **COMPOSITE:** Layer the isolated garment from step 1 over the target area on the user from INPUT 1.\n4.  **ADAPT GARMENT:** Warp, resize, and adjust the lighting on the NEW GARMENT ONLY to fit the user's exact body shape, size, and pose from INPUT 1. The user's body CANNOT be changed to fit the garment.\n5.  **FINAL VERIFICATION:** Before outputting, verify that the face, head, hair, and all visible skin in the final image are a 100% pixel-identical match to INPUT 1.\n\n**OUTPUT:**\nCreate four output images from different angles: front (standing), 3/4 left (arms relaxed), 3/4 right, and a side view. Use a neutral studio background for all outputs.",
    aspectRatio: '3:4',
  },
  {
    id: 'fitit_template_4',
    name: 'Watches',
    stackId: 'fitit',
    imageUrl: '/images/fitit_watches_cover.jpg',
    prompt: "Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Using the selfie (user not wearing a watch) and the uploaded watch photo, generate four photorealistic try-on images of the user, clearly displaying the watch on their left wrist.\nShow: front (wrist in frame, hand relaxed), side (close-up on wrist with face visible), 3/4 left (adjusting the watch), and hand resting on table (focus on watch, face smiling).\nEnsure wrist proportions are natural, the watch is integrated perfectly, and faces remain consistent across all views.\nDo not alter skin tone or add blur.",
    aspectRatio: '3:4',
  },
  {
    id: 'fitit_template_5',
    name: 'Glasses',
    stackId: 'fitit',
    imageUrl: '/images/fitit_glasses_cover (1).jpg',
    prompt: "Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Using the selfie and the uploaded glasses image, generate four crystal-clear studio portraits, each showing the user accurately wearing the glasses.\nShow: front on (head straight), slightly tilted down (natural reading pose), 3/4 left and 3/4 right (both natural smile).\nThe glasses must align precisely with the person’s face and eyes, reflections on the lenses should be natural, and there should be no blending artifacts.\nAll outputs must feature sharp facial likeness and realistic glass refraction.",
    aspectRatio: '3:4',
  },
];

const animationTemplates: Template[] = [
  {
    id: 'animation_template_1',
    name: 'Anime Figure',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1613376023733-0a7536aa4d63?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Generate an anime-style figure photo placed on a desktop, presented from a casual, everyday snapshot perspective as if taken with a mobile phone. The figure model is based on the attached character photo, accurately reproducing the full body posture, facial expression, and clothing style of the person in the photo, ensuring the entire figure is fully rendered. The overall design is exquisite and detailed, with hair and clothing featuring natural, soft gradient colors and fine textures. The style leans towards Japanese anime, rich in detail, with realistic textures, and a beautiful appearance.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_2',
    name: 'Ghibli Style',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1578351184307-e16856c14a43?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Redraw this photo in the enchanting and whimsical animation style of Studio Ghibli. Focus on soft, painterly backgrounds, expressive character designs, and a warm, nostalgic color palette.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_3',
    name: '3D Chibi Polaroid',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1629822355420-10a45937a353?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Convert the character in the scene into a 3D chibi-style figure, placed inside a Polaroid photo. The photo paper is being held by a human hand. The character is stepping out of the Polaroid frame, creating a visual effect of breaking through the two-dimensional photo border and entering the real-world 3D space.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_4',
    name: 'Stepping Through',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1531379415763-6c7414da4546?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A 3D chibi-style version of the person in the photo is stepping through a glowing portal, reaching out and holding the viewer’s hand. As the character pulls the viewer forward, they turn back with a dynamic glance, inviting the viewer into their world.\nBehind the portal is the viewer’s real-life environment: a typical programmer’s study with a desk, monitor, and laptop, rendered in realistic detail. Inside the portal lies the character’s 3D chibi world, inspired by the photo, with a cool blue color scheme that sharply contrasts with the real-world surroundings.\nThe portal itself is a perfectly elliptical frame glowing with mysterious blue and purple light, positioned at the center of the image as a gateway between the two worlds.\nThe scene is captured from a third-person perspective, clearly showing the viewer’s hand being pulled into the character’s world. Use a 2:3 aspect ratio.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_5',
    name: 'LEGO Minifigure',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1559899479-58a794025a4d?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Generate a vertically-oriented image based on my uploaded photo, using the following prompt:\nClassic LEGO minifigure style in a miniature scene — an animal stands beside me. The color palette of the animal should match mine.\nPlease design the animal based on your understanding of me. You may choose any creature — real, surreal, or fantastical — that you feel best reflects my personality.\nThe entire scene is set within a transparent glass cube, with a minimalist interior design.\nThe base of the miniature is matte black with silver accents, following a clean and modern aesthetic.\nOn the base, there is an elegantly engraved nameplate in a refined serif font, displaying the name of the animal.\nThe lower part of the base subtly incorporates finely etched biological classification details, similar to a natural history museum display.\nThe overall composition should resemble a high-end collectible artwork: meticulously crafted, curated in style, and lit with refined lighting.\nBalance is key to the layout. The background should feature a smooth gradient transition from dark to light tones, selected to match the dominant color theme.",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_6',
    name: 'Anime Badge',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1611894982245-42a138679b33?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Based on the person in the attachment, generate a photo of an anime-style badge. Requirements:\nMaterial: Tassel\nShape: Circular\nMain subject: A hand holding the badge",
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_7',
    name: 'Pixar 3D Style',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1200&auto=format&fit=crop',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. Redraw the person in this photo in the iconic Pixar 3D animation style. Focus on expressive, rounded features, detailed textures, and cinematic lighting to bring them to life as a beloved character.',
    aspectRatio: '3:4',
  },
  {
    id: 'animation_template_8',
    name: 'Chibi Sticker Sheet',
    stackId: 'animation',
    imageUrl: 'https://images.unsplash.com/photo-1620027582882-c34015f6b3e7?q=80&w=1200&auto=format&fit=crop',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Please create a set of 9 Chibi stickers featuring [the character in the reference image], arranged in a 3x3 grid.\nDesign requirements:\n- Transparent background.\n- 1:1 square aspect ratio.\n- Consistent Chibi Ghibli cartoon style with vibrant colors.\n- Each sticker must have a unique action, expression, and theme, reflecting diverse emotions like \"sassy, mischievous, cute, frantic\" (e.g., rolling eyes, laughing hysterically on the floor, soul leaving body, petrified, throwing money, foodie mode, social anxiety attack). Incorporate elements related to office workers and internet memes.\n- Each character depiction must be complete, with no missing parts.\n- Each sticker must have a uniform white outline, giving it a sticker-like appearance.\n- No extraneous or detached elements in the image.\n- Strictly no text, or ensure any text is 100% accurate (no text preferred).",
    aspectRatio: '1:1',
  },
];

const aestheticsTemplates: Template[] = [
  {
    id: 'aesthetics_template_2',
    name: 'Warm Rustic Interior',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_warmrusticinterior_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in rustic surroundings with brick walls, wood grains, and soft sunset glow, subtle earth tones. no neon colors, no artificial blur, no plastic textures, no modern city elements.no change in hairstyle , no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_3',
    name: 'Urban Alleyway Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_urbanalleywaypotrait_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} posing confidently in a textured alleyway, graffiti walls, wet reflective street, cinematic contrast lighting, modern travel-magazine tone.\nno fantasy look, no flat lighting, no distortion, no extra people.no change in hairstyle , no background blur.",
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_4',
    name: 'Vibrant Fabric Market',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_vibrantfabricmarket_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding.  {input person} sitting inside a vibrant fabric market filled with colorful textiles, patterned cloth rolls, and detailed handmade materials, wearing realistic casual matching travel clothing that fits their body naturally, warm ambient lighting, rich textures, and lively market depth, captured in clean street-photography style.no altered face,no fatty face, no altered jawline, no change in hairstyle, no pasted clothes, no blur background, no cartoon colors, adjust body posture and hand gestures naturally for a market visitor',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_5',
    name: 'Royal Luxury Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_royalluxury_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} wearing regal attire that perfectly complements the elegant royal surroundings — marble floors, velvet drapes, gold accents, graceful posture, classic Raymond luxury portrait style. bend the person and the background perfectly\nno fantasy castle, no cartoon gold, no bright glare, no blur. no change in hairstyle, no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_6',
    name: 'Forest Sunlight Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/astheics_forestsunlight_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} surrounded by forest greens and soft sunlight filtering through leaves, grounded natural pose, fresh cinematic tone like a National Geographic portrait.\nno foggy haze, no overexposure, no fake greenery, no flat tones. no change in hairstyle, no background blur. make him touch a tree with one hand',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_8',
    name: 'Ancient Monument Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_ancientmonument_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in traditional attire before an ancient monument or market street, warm daylight, authentic textures, respectful elegant posture, National Geographic realism.\nno artificial props, no fantasy color, no blur, no mixed cultural elements, no change in hairstyle, no background blur. make person join his hand and bow his head',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_9',
    name: 'Seaside Golden Hour',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_seasidegoldenhour_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} by the seaside or cliffside boardwalk, wind in hair and fabric, soft golden-hour tones, reflective water highlights, cinematic tranquility.\nno flat sky, no digital artifacts, no over-bright waves, no harsh shadows ,no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_10',
    name: 'Artistic Studio Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_artisticstudiopotrait_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a textured artistic studio backdrop, controlled soft lighting, creative shadow play, fine-grain realism, magazine-cover tone, make him look in an isometric direction, with gradient shades.\nno uneven lighting, no excessive contrast, no blur, no clutter, no change in hairstyle ,no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_11',
    name: 'Elegant Silk Saree',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_elegentsilksaree_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in an elegant silk saree with subtle jewelry, soft golden daylight, traditional Indian interior or temple courtyard, graceful posture, cinematic realism, Raymond-style sophistication.\nno overexposure, no heavy ornaments, no cartoon colors, no background blur.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_13',
    name: 'Bohemian Chic',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_bohemia_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in layered bohemian fabrics and patterns, soft evening sunlight, textured studio or artistic street market setting, natural smile, free-spirited hyper realistic image.\nno neon tones, no clutter, no artificial blur, no plastic texture , no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_14',
    name: 'Evening Gown Twilight',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_eveninggowntwilight_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a flowing satin gown, standing in a softly lit ballroom or terrace at twilight, subtle reflections, rich color contrast, high-end magazine style realism.\nno glare, no fantasy glow, no distorted proportions, no over-saturation. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_15',
    name: 'Modern Casual City',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_moderncasualcity_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in modern casual wear — jeans, light top, sneakers — city backdrop with graffiti walls or cozy café vibe, relaxed pose, cinematic lifestyle look.\nno washed-out colors, no messy framing, no extra people, no cartoon tone. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_16',
    name: 'Vintage 1950s Style',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_vintage1950_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a 1950s-inspired dress, vintage car or old café in background, warm muted tones, nostalgic mood, hyper-realistic Raymond heritage tone.\nno digital artifacts, no bright neon, no blur, no modern elements. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_18',
    name: 'Pastel Professional',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_pastelprofessional_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in light pastel blouse and trousers, airy daylight studio, subtle pastel background, Raymond lifestyle tone, clean lines, professional yet approachable look.\nno harsh lighting, no color oversaturation, no cartoon tone, no blurriness. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_19',
    name: 'Serene Landscape Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_scerenelandscape_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in simple earthy outfit surrounded by tall grass or mountain landscape, golden-hour sunlight, serene composition, cinematic National Geographic realism.\nno fog blur, no harsh shadows, no flat lighting, no digital noise. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
  {
    id: 'aesthetics_template_20',
    name: 'Dramatic Studio Portrait',
    stackId: 'aesthetics',
    imageUrl: '/images/asthetics_dramaticstudiopotrail_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} posing in an artistic indoor setup with textured painted backdrop, soft spot lighting, dramatic shadows, portrait realism with magazine clarity.\nno uneven tone, no distortion, no harsh contrast, no clutter. no background blur, change the hand gestures according to the background, no change in hairstyle.',
    aspectRatio: '3:4',
  },
];


const celebrationTemplates: Template[] = [
    {
      id: 'celebration_template_2',
      name: 'Diwali Celebration',
      stackId: 'celebration',
      imageUrl: '/images/celebration_diwali_cover.jpg',
      prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} in a realistic Diwali-themed photo setup, wearing a well-fitted festive kurta or ethnic attire that naturally adapts to the body. Hands must be posed interactively, such as gently holding a lit diya, placing a diya on the floor, or arranging small decorative lamps. Background must be crisp and clearly visible, featuring real elements like rangoli patterns, brass lamps, fairy-light strings, or a traditional courtyard with warm ambient lighting. The warm glow from diyas must cast natural, soft highlights on the person’s face and clothing, matching the lighting direction of Input Image 1. Shadows must be grounded and physically accurate. Skin tone must remain completely natural with no stylization. Photographic realism only. no altered face, no changed facial features, no hairstyle changes, no blurry background, no artificial light halos, no overexposed highlights, no cinematic color grading, no floating diyas, no surreal lighting.",
      aspectRatio: '3:4',
    },
    {
      id: 'celebration_template_3',
      name: 'Cozy Christmas Portrait',
      stackId: 'celebration',
      imageUrl: '/images/clebration_cozycristmas_cover.jpg',
      prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A cozy festive portrait of the person from the provided photo, seamlessly placed beside a beautifully decorated Christmas tree, standing on a floor or a cozy rug. It is crucial that the warm, yellow lights from the tree cast soft, realistic highlights and colored light spill onto the person, with lighting and shadows that perfectly match. The figure must be grounded with soft, diffused contact shadows on the floor/rug. The edges of the person must be seamlessly blended into the cozy scene, with no hard outlines. The scene is adorned with sparkling ornaments and wrapped gifts. The subject wears stylish winter attire. Critically, the person's face, features, and hairstyle must be an exact, photorealistic match of the original photo and must not be altered. Negative prompt: no cartoon style, no Santa hats on random objects, no duplicate faces, no messy composition, no altered faces, no changed facial features.",
      aspectRatio: '1:1',
    },
    {
      id: 'celebration_template_4',
      name: 'Holi Celebration',
      stackId: 'celebration',
      imageUrl: '/images/celebration_holi_cover.png',
      prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding {input person} in a realistic Holi-themed photo setup, wearing a well-fitted festive kurta that naturally adapts to the body. Hands must be posed interactively, such as gently holding a plate of dry gulal, offering a small pinch of color, or resting near festive props in a natural way. Background must be crisp and clearly visible, featuring real elements like bowls of gulal, marigold garlands, brass pots, or a decorated courtyard. No flying colors in the air. Skin must look completely natural with only a light touch of dry color on the cheeks and clothing. Lighting must match Input Image 1 with accurate direction and grounded shadows. Photographic realism only. no altered face, no changed facial features, no hairstyle changes, no blurry background, no atmospheric powder, no unrealistic glow, no cinematic filters, no messy colors.",
      aspectRatio: '3:4',
    },
    {
      id: 'celebration_template_5',
      name: 'Elegant Eid Portrait',
      stackId: 'celebration',
      imageUrl: '/images/celebration_eid_cover.jpg',
      prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} in a realistic Eid celebration setting, wearing a well-fitted traditional kurta or sherwani that naturally adapts to the body. Hands must be posed interactively, such as gently offering a plate of dates, adjusting the cuff, or holding a small decorative lantern. Background must be crisp and clearly visible, featuring real elements like patterned archways, soft ambient lights, carpets, or subtle Islamic geometric decor. Lighting must be warm and natural, with shadows and highlights matching the original direction from Input Image 1. The figure must be fully grounded with accurate contact shadows. Skin tone must remain natural and unchanged, and the face must be an exact photorealistic match of Input 1. no altered face, no revised facial features, no hairstyle changes, no blurry backgrounds, no glowing halos, no surreal lighting, no fantasy props, no cinematic grading.",
      aspectRatio: '3:4',
    },
];

const clothesTemplates: Template[] = [
  {
    id: 'clothes_template_1',
    name: 'Maharaja Majesty',
    stackId: 'clothes',
    imageUrl: '/images/clothes_maharajamajesty_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A realistic image of {input person} wearing a traditional Indian Maharaja outfit — embroidered sherwani with regal turban, intricate jewelry, and rich velvet texture. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly integrated, standing realistically on a clean studio floor with accurate contact shadows. The warm studio lighting must realistically wrap around the subject, matching the color temperature and creating cohesive highlights and shadows for a believable portrait.  Raymond fashion . Ultra-sharp fabric detail, lifelike skin tone. no cartoon embroidery, no plastic jewelry, no harsh flash, no duplicate faces, no low-quality fabric texture, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_2',
    name: 'Classic Tailored Suit',
    stackId: 'clothes',
    imageUrl: '/images/clothes_classictailoredsuit_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} in a tailored charcoal or navy suit with white shirt and silk tie. The person's face and features must be an exact match of the provided photo, without any alterations. Their integration into the studio setup must be seamless, with their feet firmly planted, casting a soft, realistic shadow. The soft studio lighting on the subject should perfectly match the subtle gradient background, creating realistic dimensionality and soft shadows. Editorial-grade Raymond-style realism, 8K cinematic photography, balanced highlights, lifelike shadowing, clean grooming, polished texture.\nno exaggerated contrast, no wrinkled suit, no off-tone skin, no duplicate background, no low detail, no change in hairstyle, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_3',
    name: 'Business Casual',
    stackId: 'clothes',
    imageUrl: '/images/clothes_businesscasual_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A professional portrait of {input person} in business casual attire — light blazer, rolled-sleeve shirt, and chinos. The person's face and features must be an exact match of the provided photo, without any alterations.The person should be realistically placed in the scene, with the natural daylight from the window creating believable highlights and soft shadows on them that perfectly match the color and direction of the light in the office background. The result should be a cohesive, cinematic, and sharp image with a seamless blend between the subject and the environment. Raymond-style color grading.\nno cluttered background, no cartoon tone, no distorted fabric folds, no mixed lighting, no change in hair style, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_4',
    name: 'Modern Festive Kurta',
    stackId: 'clothes',
    imageUrl: '/images/clothes_modernfestivekurta_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} wearing a modern festive kurta in clean, elegant colors, standing in a softly decorated contemporary festive setting with warm ambient lights, minimal floral elements, and refined cultural aesthetics. The kurta must fit the person's real body shape and proportions naturally, with accurate fabric texture and subtle festive detailing.\nno altered face, no change in hairstyle, no pasted-on clothing, no over-saturated colors, no blur background, adjust posture and hand gestures naturally for a graceful festive moment.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_6',
    name: 'Premium Winter Fashion',
    stackId: 'clothes',
    imageUrl: '/images/clothes_premiumwinterfashion_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} dressed in premium winter fashion — wool coat, turtleneck, and scarf. The person's face and features must be an exact match of the provided photo, without any alterations. They must be perfectly blended with the neutral tone background, with soft, cool-toned directional lighting creating subtle, realistic shadows on their form and attire that match the neutral background. Cinematic Raymond ad aesthetic, hyper-realistic texture, 85 mm lens photo realism.\nno overly dark tones, no duplicate coats, no blur, no fantasy lighting,no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_9',
    name: 'Summer Linen',
    stackId: 'clothes',
    imageUrl: '/images/clothes_summerlinen_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A lifestyle portrait of {input person} in a light linen shirt and chinos. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be naturally blended into the sunny outdoor ambience, with soft daylight filtering through leaves to cast realistic, dappled shadows on them, ensuring the light's color and intensity match a sunny outdoor setting. Raymond summer campaign aesthetic, photorealistic tone, clean colors.\nno sweat, no cartoon tones, no distorted hands, no unrealistic lighting, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_10',
    name: 'Silk Saree',
    stackId: 'clothes',
    imageUrl: '/images/clothes_silksaree_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A hyper-realistic portrait of {input person} wearing a rich silk saree with detailed zari border, styled hair and traditional jewelry. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly integrated with the minimal studio background. Soft, warm studio lighting should realistically illuminate the subject and the fabric's texture, creating cohesive highlights and shadows for a cinematic, editorial-style image. Ultra-sharp texture and lifelike folds.\nno plastic jewelry, no over-saturated reds, no cartoon shine, no duplicate drapes,no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_11',
    name: 'Evening Gown',
    stackId: 'clothes',
    imageUrl: '/images/clothes_gown_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} in a flowing evening gown. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be seamlessly placed against the subtle gradient backdrop. Elegant studio light must create smooth, realistic highlights and shadows on the fabric that give it form and depth against the backdrop. High-fashion cinematic tone.\nno blur, no fantasy sparkles, no duplicated arms, no overexposure, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_12',
    name: 'Tailored Blazer',
    stackId: 'clothes',
    imageUrl: '/images/clothes_tailoredblazor_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A professional portrait of {input person} in a tailored blazer and trousers. The person's face and features must be an exact match of the provided photo, without any alterations. The person should be realistically blended with the minimal office backdrop, with soft, neutral studio lighting creating crisp folds and natural shadows for a cohesive, editorial look against the minimal backdrop. Raymond ad realism, professional fashion tone.\nno harsh reflections, no messy hair, no blur, no distorted proportions, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_13',
    name: 'Boho Dress',
    stackId: 'clothes',
    imageUrl: '/images/clothes_bohodress_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} wearing a flowy printed boho dress with light accessories. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be naturally integrated into the outdoor scene, with daylight realistically filtering through foliage to create warm sun flares and soft, dappled shadows on them, perfectly matching an outdoor, sunny environment. National Geographic × Raymond cinematic realism, soft natural tones, ultra-detailed texture.\nno fake patterns, no crowd, no lens flare over face, no heavy color grading, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_14',
    name: 'Knit Turtleneck',
    stackId: 'clothes',
    imageUrl: '/images/clothes_turtleneck_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} dressed in a wool coat, knit turtleneck, and scarf. The person's face and features must be an exact match of the provided photo, without any alterations. They must be seamlessly blended into the studio setting, with soft, cool-toned studio light creating realistic, cinematic shadows that match the winter fashion theme. Premium Raymond-style realism, fabric grain visible in 8K detail.\nno dark noise, no blur, no exaggerated cold tone, no duplicate coat layers,no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_16',
    name: 'Bridal Lehenga',
    stackId: 'clothes',
    imageUrl: '/images/clothes_bridallahenga_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A National Geographic-grade image of {input person} in a detailed bridal lehenga. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly composited, with intricate embroidery shining realistically under soft golden light, ensuring the highlights and shadows on the subject are cohesive with the light source. The lighting should create a natural elegance and a gentle background blur for a cohesive look. Raymond ad color tone, hyper-realistic textures.\nno duplicate faces, no plastic shine, no artificial color filters, no glare, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'clothes_template_17',
    name: 'Pastel Blouse',
    stackId: 'clothes',
    imageUrl: '/images/clothes_pastelblouse_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} in light pastel blouse and trousers. The person's face and features must be an exact match of the provided photo, without any alterations. The person must be seamlessly integrated into the airy daylight studio setting. The bright, airy studio lighting and subtle pastel background should create a clean, professional, and cohesive image, with soft, flattering shadows. Raymond lifestyle aesthetic, cinematic realism.\nno harsh lighting, no color oversaturation, no cartoon tone, no blurriness, no change in hairstyle , no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
];

const flexTemplates: Template[] = [
  {
    id: 'flex_template_1',
    name: 'Bugatti Coastal Drive',
    stackId: 'flex',
    imageUrl: '/images/flex_bugaticostaldrive_cover.png',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a tailored suit or premium jacket, posing beside or driving a Bugatti on a scenic coastal highway, sunlight reflecting off polished metal, wind-in-motion realism, Raymond-class sophistication.\nno motion blur, no fantasy reflections, no cartoon look, no harsh shadows.',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_2',
    name: 'Luxury Superbike Rider',
    stackId: 'flex',
    imageUrl: '/images/flex_luxurysuperbikerider_cover.png',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in sleek riding gear with a luxury superbike (like Ducati, BMW, or Hayabusa), mountains in background, real fabric and metal textures, confident Raymond posture.no artificial glow, no blur, no color oversaturation, no background noise, no change in hairstyle, no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_3',
    name: 'Ice Rink Elegance',
    stackId: 'flex',
    imageUrl: '/images/flex_icerink_cover.png',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} gliding across a glassy ice rink wearing a stylish winter outfit — wool coat, gloves, and scarf, soft white lighting, reflections on ice, hyper-real fabric and frost details, serene elegance, each background object should be clearly visible. no background blur, no fantasy snow, no overexposure, no messy reflections.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_4',
    name: 'Deep Sea Diver',
    stackId: 'flex',
    imageUrl: '/images/flex_deepdive_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in full-body deep-sea diving gear that fits their body naturally, underwater with realistic blue ambient light, floating particles, coral textures, soft rays filtering through water, and true-to-life diving posture, captured in high-detail ocean-photography style.\nno altered face, no change in hairstyle (if visible), no pasted clothes, no cartoonish colors, no blur background, adjust body posture and hand gestures naturally for a diver',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_5',
    name: 'Private Jet Lifestyle',
    stackId: 'flex',
    imageUrl: '/images/flex_privatejet_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} standing next to a private jet door and leaning back slightly, one hand in pocket, dressed in formal-casual attire — blazer and sunglasses, golden sunset light, tarmac reflections, refined Raymond elegance and cinematic composition, background objects should be clearly visible with no blurness(most important). no glare, no distorted jet, no cartoon tones, no excessive brightness.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_6',
    name: 'Yacht Life',
    stackId: 'flex',
    imageUrl: '/images/flex_yachtlife_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} on a luxury yacht deck wearing linen shirt or summer blazer, calm blue ocean background, sunlight reflections on water, clean cinematic tones, National Geographic-style travel luxury.\nno haze, no overexposure, no blur, no unrealistic waves.no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_7',
    name: 'City Night Supercar',
    stackId: 'flex',
    imageUrl: '/images/flex_citynight_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a black or navy blazer, leaning on a Lamborghini or McLaren under neon city lights which are clearly visible, cinematic reflections on car surfaces, confident luxury tone, editorial realism. no cartoon neon, no fantasy lighting, no distortion, no change in hairstyle , no blur background, change the hand gestures accordingly',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_8',
    name: 'Desert ATV Adventure',
    stackId: 'flex',
    imageUrl: '/images/flex_desertatv_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} sitting inside an ATV across a wide desert landscape, wearing realistic outdoor adventure clothing (without helmet) that fits their body naturally, sharp sunlight, sand trails, heat shimmer,clearly visible dunes in the background, captured in static real photography style.no altered face, no change in hairstyle, no pasted clothes, no blur background, no oversaturated colors, adjust body posture and hand gestures naturally for an ATV rider.',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_9',
    name: 'Sunset Convertible Drive',
    stackId: 'flex',
    imageUrl: '/images/flex_sunsetdrive_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} driving a convertible through a scenic coastal road at sunset, soft warm light, detailed car reflections, relaxed posture, cinematic Raymond tone of leisure and freedom.\nno glare, no blur, no fantasy colors, no distorted vehicle.no change in hairstyle , no blur background, change the hand gestures accordingly . whole face should be visible',
    aspectRatio: '4:3',
  },
  {
    id: 'flex_template_10',
    name: 'Luxury Hotel Lounge',
    stackId: 'flex',
    imageUrl: '/images/flex_LuxuryHotelLounge_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a formal blazer or elegant dress, seated in a luxurious hotel lounge with warm ambient lighting, marble tables, golden tones, cinematic realism, Raymond lifestyle grace and poise.\nno harsh light, no blur, no busy crowd, no cartoon textures.no change in hairstyle , no blur background, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_11',
    name: 'Premium Wristwatch',
    stackId: 'flex',
    imageUrl: '/images/flex_premiumwristwatch_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} adjusting a premium wristwatch (Rolex, Omega, etc.), wearing a fitted suit, soft golden light highlighting metallic reflections, focus on texture and class, Raymond editorial clarity.\nno overexposure, no fingerprints glare, no blur, no fantasy glow.no change in hairstyle , no  background blur, change the hand gestures accordingly. whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_12',
    name: 'Luxury Shopping Spree',
    stackId: 'flex',
    imageUrl: '/images/flex_luxuryshoppingspree_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} walking through a luxury shopping district or high-end boutique, holding branded shopping bags, stylish modern outfit, cinematic natural lighting and color realism.\nno crowd, no harsh neon, no motion blur, no washed tones. no change in hairstyle , no  background blur, change the hand gestures accordingly. whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_13',
    name: 'Infinity Pool Villa',
    stackId: 'flex',
    imageUrl: '/images/flex_infinitypoolvilla_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} relaxing in a private villa terrace with infinity pool, wearing casual linen attire, golden sunlight reflecting on water, serene Raymond lifestyle tone, high-end vacation realism ,8k quality image .\nno unrealistic sky, no blur, no fantasy pool reflection, no saturation spike. no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_14',
    name: 'Morning Coffee & Journal',
    stackId: 'flex',
    imageUrl: '/images/flex_morningcoffe_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} sitting beside a wooden table with a coffee cup and leather journal, warm morning light streaming in, casual yet refined outfit, Raymond editorial lifestyle clarity.\nno low-light noise, no over-bright mug, no harsh shadows, no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_15',
    name: 'Modern Gym Session',
    stackId: 'flex',
    imageUrl: '/images/flex_moderngym_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} in a sleek modern gym, wearing premium sportswear, cinematic light streaks across metal equipment, posture showing focus and discipline, Raymond athletic luxury vibe.\nno cluttered background, no blur, no over-saturation, no artificial tone. no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_16',
    name: 'Fine Dining Experience',
    stackId: 'flex',
    imageUrl: '/images/flex_finedining_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} at a fine dining table, elegant evening wear, candlelight and reflections from wine glasses, warm cinematic tone, Raymond lifestyle luxury captured with realism.\nno messy background, no glare, no fantasy color, no blur. no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_17',
    name: 'Luxury Hotel Suite',
    stackId: 'flex',
    imageUrl: '/images/luxuryhoetlsuite.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} relaxing or preparing in a high-end suite, elegant interior textures, soft lamp light and silk bedding, refined comfort and subtle cinematic warmth, Raymond-class composition.\nno harsh lighting, no blur, no fake props, no color imbalance.no change in hairstyle , no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
  {
    id: 'flex_template_18',
    name: 'Race Track Ferrari',
    stackId: 'flex',
    imageUrl: '/images/flex_racetrackferrari_cover.jpg',
    prompt: 'Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure\'s face matches sharply with the input figure\'s face, preserving the exact chin shape and jawline without rounding. {input person} standing beside a red Ferrari in a race track pit wearing a tailored race suit, dynamic composition, crisp sunlight, polished reflections, hyper-realistic fashion-meets-speed vibe, Raymond luxury tone.\nno lens distortion, no cartoon color, no blur, no empty background, no plastic reflections..no  background blur, change the hand gestures accordingly . whole face should be visible .',
    aspectRatio: '3:4',
  },
];

const monumentsTemplates: Template[] = [
  {
    id: 'monuments_template_1',
    name: 'Taj Mahal Sunrise Portrait',
    stackId: 'monuments',
    imageUrl: '/images/monuments_tajmahal_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A hyper-realistic portrait of the person from the provided photo, seamlessly composited onto the marble walkway near the Taj Mahal at sunrise. Critically, their face, features, and hairstyle must be an exact, photorealistic match to the user's photo and must not be altered. The lighting on them must perfectly match the color temperature and soft quality of the sunrise, with highlights and shadows consistent with the sun's direction. Their feet must be firmly on the ground, casting a soft, accurate contact shadow on the marble. Their edges must be seamlessly blended with the misty background. Digitally dress them in elegant Indian travel attire. The background shows the Yamuna River mist, with a calm, majestic atmosphere. Cinematic 8K detail. \nno washed-out sky, no tourists, no fake reflections, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_2',
    name: 'Eiffel Tower Romance',
    stackId: 'monuments',
    imageUrl: '/images/monuments_ifeltowerromance_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Place the person from the photo in a romantic, cinematic scene in Paris, with the Eiffel Tower in the background at golden hour. The person's face, features, and hairstyle must be preserved with photorealistic accuracy and must not be altered. The person must be seamlessly composited, for example, leaning realistically on a classic Parisian balcony railing. The warm, golden hour light must wrap around the subject naturally, creating soft highlights and shadows that match the color temperature and direction of the ambient light. Ensure their edges are soft and perfectly blended into the background. Digitally dress them in chic, stylish attire. The mood should be dreamy and romantic, with a shallow depth of field. \nno altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_3',
    name: 'Pyramids of Giza Expedition',
    stackId: 'monuments',
    imageUrl: '/images/monuments_pyramidsofgyza_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Create a grand, adventurous shot of the person from the photo, seamlessly integrated into the scene at the Pyramids of Giza. Their face, features, and hairstyle must remain identical to the uploaded photo and not be altered. They must be standing firmly on the desert sand, with the bright desert sun casting strong, realistic shadows that ground them in the environment. The lighting on the person must match the harsh, direct sunlight of the desert. Ensure their edges are cleanly blended against the background. Position them as an explorer in practical clothing. The final image should feel like a still from an epic adventure movie. \nno altered faces, no changed facial features.",
    aspectRatio: '16:9',
  },
  {
    id: 'monuments_template_4',
    name: 'Statue of Liberty Welcome',
    stackId: 'monuments',
    imageUrl: '/images/monuments_statueofliberty_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Create a powerful portrait of the person from the photo, seamlessly placed on a paved pathway on Liberty Island, with the Statue of Liberty in the background. Maintain the person's facial features and hairstyle with absolute accuracy; do not alter them. They must be realistically grounded with shadows that are consistent with the bright daylight. The lighting on the person must perfectly match the bright, outdoor daylight. Ensure their silhouette is cleanly and seamlessly blended with the background. Digitally dress them in casual tourist attire. The image should be crisp, clear, and vibrant. \nno altered faces, no changed facial features.",
    aspectRatio: '4:3',
  },
  {
    id: 'monuments_template_5',
    name: 'Great Wall of China Trek',
    stackId: 'monuments',
    imageUrl: '/images/monuments_greatwallofchina_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Place the person from the photo onto a majestic section of the Great Wall of China. The person's face and hairstyle must be an exact match to the input photo and must not be altered. They must be seamlessly composited, standing firmly on the stone walkway with a view of rolling mountains. The natural daylight must illuminate the person realistically, matching the color and direction of the sun, creating shadows that ground them in the scene. Their edges must be naturally blended with the background. Digitally dress them in practical trekking gear. The mood should be one of adventure and awe. \nno altered faces, no changed facial features.",
    aspectRatio: '16:9',
  },
  {
    id: 'monuments_template_6',
    name: 'Colosseum Gladiator Pose',
    stackId: 'monuments',
    imageUrl: '/images/monuments_colousium_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Compose a dramatic image of the person from the photo, seamlessly integrated into a scene before the Colosseum in Rome. Do not alter their face, features, or hairstyle. They must be standing realistically on the ground, with the golden hour light casting long, believable shadows that anchor them to the spot. The warm light must wrap around their form convincingly, matching the color temperature of the scene. Ensure their edges are clean and seamlessly blended with the background. Dress them in stylish, modern attire. The final image should be high-contrast and heroic. \nno altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_7',
    name: 'Lotus Temple Sunset Portrait',
    stackId: 'monuments',
    imageUrl: '/images/monuments_lotustemple_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Create a serene and hyper-realistic portrait of the person from the provided photo, seamlessly composited onto the walkway beside a reflecting pool at the Lotus Temple in Delhi during sunset. Their face, features, and hairstyle must be an exact, photorealistic match and must not be altered. The lighting on the person must perfectly match the soft, pastel hues of the sunset sky, with realistic highlights and their reflection subtly visible in the water. They must be grounded with soft contact shadows consistent with the evening light. Critically, their edges must be flawlessly blended into the background to create a photorealistic composite. Digitally dress them in modern, elegant attire. The composition must capture the temple's reflection in the water. The style should be inspired by National Geographic's photojournalism. The final image must be cinematic, with natural lighting. \nno altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'monuments_template_8',
    name: 'Machu Picchu Sunrise Explorer',
    stackId: 'monuments',
    imageUrl: '/images/monuments_machupichu_cover.jpg',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A hyper-realistic travel portrait of the person from the provided photo, seamlessly integrated into the Machu Picchu ruins at sunrise. Their face, features, and hairstyle must be an exact match to the user's photo and must not be altered. They must be standing firmly on an ancient stone path or grassy terrace, with the dramatic sunlight streaming through the peaks casting realistic highlights and shadows on them that match the light direction and color. Ensure their integration is seamless, grounding them with accurate contact shadows and perfectly anti-aliased edge blending to create a cohesive, photorealistic image. Digitally dress them in practical trekking gear. The style should be a National Geographic hyper-realistic travel portrait with a grand, cinematic feel. \nNo other tourists, no haze, no over-saturated greens, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
];

const sceneriesTemplates: Template[] = [
  {
    id: 'sceneries_template_1',
    name: 'Himalayan Trek',
    stackId: 'sceneries',
    imageUrl: '/images/sceneries_himalayantreck_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A hyper-realistic portrait of {input person} trekking through the Himalayas, wearing layered hiking gear. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: snow-dusted trail, majestic mountains in the background, sunlight piercing thin clouds, cinematic tone mapping, National Geographic photo realism, crisp focus, earthy textures, adventure mood.\nno unrealistic lighting, no floating person, no cartoon effects, no duplicate faces, no overexposure, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_2',
    name: 'Sahara Desert Walk',
    stackId: 'sceneries',
    imageUrl: '/images/sceneries_saharadesertwalk_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. A photo of {input person} walking across vast golden dunes in the Sahara Desert, carrying a backpack. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: soft sunlight casting long shadows, sand patterns crisp and realistic, warm tones, National Geographic composition, cinematic atmosphere.\nno mirage effects, no sandstorm, no missing limbs, no unnatural shadows, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_3',
    name: 'Amazon Rainforest Explorer',
    stackId: 'sceneries',
    imageUrl: '/images/sceneries_amazonrainforest_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding.{input person} exploring deep inside the Amazon rainforest, wearing realistic lightweight explorer clothing that fits their body naturally, lush green foliage, dense canopy light rays, humid atmosphere, vines, mossy trees, and rich jungle textures, captured in natural adventure-photography style.\nno altered face, no change in hairstyle, no pasted clothes, no blur background, no fantasy colors, adjust body posture and hand gestures naturally for an explorer.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_5',
    name: 'Icelandic Waterfall',
    stackId: 'sceneries',
    imageUrl: '/images/sceneries_icelandicwaterfall_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} standing on rocky ground near a massive Icelandic waterfall, wearing realistic outdoor travel clothing that fits their body naturally, moss-covered cliffs, wide-angle adventure photography, realistic lighting and colors.no altered face, no change in hairstyle, no pasted clothes, no blur background, no fantasy colors, adjust body posture and hand gestures naturally for a traveler.",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_6',
    name: 'Moroccan Market',
    stackId: 'sceneries',
    imageUrl: '/images/sceneries_moroccanmarket_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} walking through a busy Moroccan market street, wearing realistic lightweight travel clothing that fits their body naturally, warm golden sunlight, textured stone walls, colorful stalls, patterned rugs, brass lamps, spices, and traditional architecture, shot in natural street-photography style.\nno altered face, no change in hairstyle, no pasted clothes, no blur background, no fantasy colors, adjust body posture and hand gestures naturally for a traveler",
    aspectRatio: '3:4',
  },
  {
    id: 'sceneries_template_7',
    name: 'Aurora Borealis Night',
    stackId: 'sceneries',
    imageUrl: '/images/sceneries_auroraborealis_cover.png',
    prompt: "Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. {input person} standing in front of aurora borealis under a starry night sky, wearing winter clothing. The person's face, features, and hairstyle must be an exact match to the provided photo and must not be altered. Scene details: snow reflecting green and purple light, crisp cinematic clarity, National Geographic hyper-realistic tone, emotional composition.\nno artificial sky patterns, no cartoon aurora, no exposure burn, no fantasy style, no change in hairstyle, no background blur, no altered faces, no changed facial features.",
    aspectRatio: '3:4',
  },
];

// Fallback for any other stacks to ensure they have content
const allStackIds = STACKS.map(s => s.id);
const definedStackIds = ['fitit', 'animation', 'aesthetics', 'celebration', 'clothes', 'flex', 'monuments', 'sceneries'];
const remainingStackIds = allStackIds.filter(id => !definedStackIds.includes(id));

const placeholderTemplates = remainingStackIds.flatMap(stackId => {
  const stack = STACKS.find(s => s.id === stackId)!;
  return Array.from({ length: 4 }, (_, i): Template => ({
    id: `${stack.id}_template_${i + 1}`,
    name: `${stack.name} Style ${i + 1}`,
    stackId: stack.id,
    imageUrl: `https://picsum.photos/seed/${stack.id}${i}/1200/900`,
    prompt: `Make sure the background of the output image is not blurry and the output image has clearly visible background objects. Ensure the output figure's face matches sharply with the input figure's face, preserving the exact chin shape and jawline without rounding. Transform the user's image with a professional ${stack.name.toLowerCase()} aesthetic, style ${i+1}. Focus on composition and high-quality details.`,
    aspectRatio: '3:4',
  }));
});


export const TEMPLATES: Template[] = [
  ...fititTemplates,
  ...animationTemplates,
  ...aestheticsTemplates,
  ...celebrationTemplates,
  ...clothesTemplates,
  ...flexTemplates,
  ...monumentsTemplates,
  ...sceneriesTemplates,
  ...placeholderTemplates,
];
